language: r
sudo: false
cache: packages

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'utils::packageVersion("Signac")'

os:
  - windows
  - linux
  - osx

notifications:
  email:
    on_success: change
    on_failure: change

